version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "jossmoff"
    commit-message:
      prefix: "⬆️"
    labels:
      - "dependencies"